name: flash-cards
base: core24
version: '0.1'
summary: Flash Cards
description: |
  Flash Cards provides a simple interface for reviewing that ever so
  important study material. With intuitive keyboard controls to switch
  between cards and show definitions as well as toggle full screen mode
  for distraction free studying.

  Includes a built-in editor to create your decks of flash cards as well
  as edit existing decks.

  Flash Cards reads terms and definitions from simple JSON formated files.

grade: stable
confinement: strict
contact: https://github.com/kenvandine/flash-cards/issues
issues: https://github.com/kenvandine/flash-cards/issues
website: https://github.com/kenvandine/flash-cards
license: GPL-3.0+
icon: icon.png

platforms:
  amd64:
  arm64:

parts:
  flash-cards:
    plugin: nil
    source: .
    override-build: |
      cp *.py $CRAFT_PART_INSTALL/
      cp -rp css $CRAFT_PART_INSTALL/
      cp {flash-cards,sample.json} $CRAFT_PART_INSTALL/
      cp icon.png $CRAFT_PART_INSTALL/

apps:
  flash-cards:
    command: flash-cards
    extensions: [ gnome ]
    plugs:
      - home
      - removable-media
