name: flash-cards
adopt-info: flash-cards
summary: Flash Cards
description: |
  Flash Cards provides a simple interface for reviewing that ever so
  important study material. With intuitive keyboard controls to switch
  between cards and show definitions as well as toggle full screen mode
  for distraction free studying.

  Includes a built-in editor to create your decks of flash cards as well
  as edit existing decks.

  Flash Cards reads terms and definitions from simple JSON formated files.

grade: stable
confinement: strict
base: core24
contact: https://github.com/kenvandine/flash-cards/issues
issues: https://github.com/kenvandine/flash-cards/issues
website: https://github.com/kenvandine/flash-cards
license: GPL-3.0+
icon: icon.png

platforms:
  amd64:
  arm64:

parts:
  flash-cards:
    plugin: meson
    source: .
    meson-parameters: [ --prefix=/usr ]
    override-pull: |
      craftctl default
      craftctl set version=$(cat meson.build | grep "version: " | awk -F "'" '{print $4}')
      cp icon.png $CRAFT_PART_INSTALL/
      mkdir -p $CRAFT_PART_INSTALL/usr/share/flash-cards/flash_cards
      cp icon.png $CRAFT_PART_INSTALL/usr/share/flash-cards/flash_cards/
      cp sample.json $CRAFT_PART_INSTALL/
    override-build: |
      craftctl default
      sed -i 's#/snap/gnome-46-2404-sdk/current/usr/bin/python3.*$#/snap/flash-cards/current/gnome-platform/usr/bin/python3.12#g' $CRAFT_PART_INSTALL/usr/bin/flash-cards

apps:
  flash-cards:
    command: usr/bin/flash-cards
    extensions: [ gnome ]
    plugs:
      - home
      - removable-media
